version: 2.1

jobs:
  node_build_checks:
    docker:
      - image: circleci/node:14
    resource_class: xlarge
    environment:
      NODE_OPTIONS: '--max_old_space_size=3584'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      # - run:
      #     name: Build
      #     command: yarn build
      - run:
          name: Install libnss3
          command: sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev
      - run:
          name: Run checks
          command: ./scripts/yarn-checks.sh

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare

  node_build_checks_workflow:
    jobs:
      - node_build_checks:
          name: "Node Build Checks"
