version: 2.1

jobs:
  node_build_checks:
    docker:
      - image: circleci/node:14
    resource_class: xlarge
    environment:
      NODE_OPTIONS: '--max_old_space_size=3584'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      # - run:
      #     name: Build
      #     command: yarn build
      - run:
          name: Install libnss3
          command: sudo apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - run:
          name: Run checks
          command: ./scripts/yarn-checks.sh

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare

  node_build_checks_workflow:
    jobs:
      - node_build_checks:
          name: "Node Build Checks"
