version: 2.1

jobs:
  node_build_checks:
    machine:
      image: ubuntu-2204:2024.01.2
    resource_class: arm.xlarge
    environment:
      NODE_OPTIONS: '--max_old_space_size=3584'
    steps:
      - checkout
      - run:
          name: Setup node
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version
            npm --version
            yarn --version
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      # - run:
      #     name: Build
      #     command: yarn build
      # - run:
      #     name: Install libnss3
      #     command: sudo apt update && sudo apt install -t bullseye libnss3 && apt show libnss3
      - run:
          name: Run checks
          command: ./scripts/yarn-checks.sh

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.8

workflows:
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare

  node_build_checks_workflow:
    jobs:
      - node_build_checks:
          name: "Node Build Checks"
